### ISSUE TITLE
Added hover effects when navigating to the tabs at top of the page

### ISSUE THREAD

**Issue by DhanushNehru** [Mayuresh-22/Minglr-Social-Network-Site#10]
HI , I have added hover effects when navigating to the tabs for better User Experience

https://github.com/Mayuresh-22/Minglr-Social-Network-Site/pull/9

**Comment by Mayuresh-22** [comment]
Great work @DhanushNehru. I will merge the request under Hacktoberfest 2023

**Comment by DhanushNehru** [comment]
Thanks @Mayuresh-22 can you add hacktoberfest-accepted label ?
