### ISSUE TITLE
Styling navbar and links.

### ISSUE THREAD

**Issue by yashi-15** [Mayuresh-22/Minglr-Social-Network-Site#6]
I would like to style the navbar and the navbar links for each page. Please assign it to me under hacktoberfest .

**Comment by Mayuresh-22** [comment]
Yeah sure I will assign you this issue under hacktoberfest 2023.

But before that setup the project as mentioned in the Readme file.

And follow these additional steps:
https://github.com/Mayuresh-22/Minglr-Social-Network-Site/issues/3#issuecomment-1742102134

If you face any sort of issue feel free to connect with me here and I'll try to solve the issue.

**Comment by Mayuresh-22** [comment]
Any updates?

**Comment by yashi-15** [comment]
Hey, I performed the steps as you mentioned, and I have reached here.

![Screenshot (27)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/132138302/c6d38cdf-d28e-4e07-9f61-c63d58bb9dd4)

What next, I need to do to finally able to make the changes into the code.

**Comment by Mayuresh-22** [comment]
Okay @yashi-15, now place this repository folder that you have cloned on your local machine into your C drive >xampp > htdocs (In short you'll get the htdocs folder in the xampp folder) and start the xampp server (Apache & MySQL)) and you are set to make the changes to the project.

**Comment by yashi-15** [comment]
I am not able to run the project as local host, getting this error:


![Screenshot (28)](https://github.com/Mayuresh-22/Minglr-Social-Network-Site/assets/132138302/8b69fd13-258d-4217-8386-8d2b496cbd0e)

**Comment by AbdullahTheDev** [comment]
Can you assign this task to me? I'll do it and you can also add hacktoberfest tag

**Comment by Mayuresh-22** [comment]
> Can you assign this task to me? I'll do it and you can also add hacktoberfest tag

Yeah sure I will assign this issue to you @AbdullahTheDev under the hacktoberfest 2023

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me too? @Mayuresh-22

**Comment by Jenis07** [comment]
can you assign it to me this projects?

**Comment by Mayuresh-22** [comment]
You all can start working on this issue and make a pull request I will merge them under Hacktoberfest 2023 (If there are no merge conflicts and PR really solves the issue)

**Comment by Mayuresh-22** [comment]
Closing this Issue
